wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.3
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1685632636.475717
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.9.16
      5: 0.15.3
      8:
      - 2
      - 5
