name: mlops-zoomcamp-env
channels:
  - defaults
dependencies:
  - ca-certificates=2023.01.10=hca03da5_0
  - libcxx=14.0.6=h848a8c0_0
  - libffi=3.4.4=hca03da5_0
  - ncurses=6.4=h313beb8_0
  - openssl=1.1.1t=h1a28f6b_0
  - pip=23.0.1=py39hca03da5_0
  - python=3.9.16=hc0d8a6c_2
  - readline=8.2=h1a28f6b_0
  - setuptools=67.8.0=py39hca03da5_0
  - sqlite=3.41.2=h80987f9_0
  - tk=8.6.12=hb8d0fd4_0
  - wheel=0.38.4=py39hca03da5_0
  - xz=5.4.2=h80987f9_0
  - zlib=1.2.13=h5a0b063_0
  - pip:
      - alembic==1.11.1
      - anyio==3.7.0
      - appdirs==1.4.4
      - appnope==0.1.3
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - asttokens==2.2.1
      - attrs==23.1.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - bleach==6.0.0
      - blinker==1.6.2
      - boto3==1.26.142
      - botocore==1.29.142
      - certifi==2023.5.7
      - cffi==1.15.1
      - charset-normalizer==3.1.0
      - cloudpickle==2.2.1
      - cmaes==0.9.1
      - colorlog==6.7.0
      - comm==0.1.3
      - contourpy==1.0.7
      - cramjam==2.6.2
      - cycler==0.11.0
      - databricks-cli==0.17.7
      - debugpy==1.6.7
      - decorator==5.1.1
      - defusedxml==0.7.1
      - docker==6.1.2
      - docker-pycreds==0.4.0
      - entrypoints==0.4
      - exceptiongroup==1.1.1
      - executing==1.2.0
      - fastjsonschema==2.17.1
      - fastparquet==2023.4.0
      - flask==2.3.2
      - fonttools==4.39.4
      - fqdn==1.5.1
      - fsspec==2023.5.0
      - future==0.18.3
      - gitdb==4.0.10
      - gitpython==3.1.31
      - gunicorn==20.1.0
      - hyperopt==0.2.7
      - idna==3.4
      - importlib-metadata==6.6.0
      - importlib-resources==5.12.0
      - ipykernel==6.23.1
      - ipython==8.13.2
      - ipython-genutils==0.2.0
      - ipywidgets==8.0.6
      - isoduration==20.11.0
      - itsdangerous==2.1.2
      - jedi==0.18.2
      - jinja2==3.1.2
      - jmespath==1.0.1
      - joblib==1.2.0
      - jsonpointer==2.3
      - jsonschema==4.17.3
      - jupyter==1.0.0
      - jupyter-client==8.2.0
      - jupyter-console==6.6.3
      - jupyter-core==5.3.0
      - jupyter-events==0.6.3
      - jupyter-server==2.6.0
      - jupyter-server-terminals==0.4.4
      - jupyterlab-pygments==0.2.2
      - jupyterlab-widgets==3.0.7
      - kiwisolver==1.4.4
      - mako==1.2.4
      - markdown==3.4.3
      - markupsafe==2.1.2
      - matplotlib==3.7.1
      - matplotlib-inline==0.1.6
      - mistune==2.0.5
      - mlflow==2.3.2
      - nbclassic==1.0.0
      - nbclient==0.8.0
      - nbconvert==7.4.0
      - nbformat==5.8.0
      - nest-asyncio==1.5.6
      - networkx==3.1
      - notebook==6.5.4
      - notebook-shim==0.2.3
      - numpy==1.24.3
      - oauthlib==3.2.2
      - optuna==3.2.0
      - overrides==7.3.1
      - packaging==23.1
      - pandas==2.0.2
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pathtools==0.1.2
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.5.0
      - platformdirs==3.5.1
      - prometheus-client==0.17.0
      - prompt-toolkit==3.0.38
      - protobuf==4.23.2
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py4j==0.10.9.7
      - pyarrow==11.0.0
      - pycparser==2.21
      - pygments==2.15.1
      - pyjwt==2.7.0
      - pyparsing==3.0.9
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pytz==2023.3
      - pyyaml==6.0
      - pyzmq==25.1.0
      - qtconsole==5.4.3
      - qtpy==2.3.1
      - querystring-parser==1.2.4
      - requests==2.31.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - s3transfer==0.6.1
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - seaborn==0.12.2
      - send2trash==1.8.2
      - sentry-sdk==1.24.0
      - setproctitle==1.3.2
      - six==1.16.0
      - smmap==5.0.0
      - sniffio==1.3.0
      - soupsieve==2.4.1
      - sqlalchemy==2.0.15
      - sqlparse==0.4.4
      - stack-data==0.6.2
      - tabulate==0.9.0
      - terminado==0.17.1
      - threadpoolctl==3.1.0
      - tinycss2==1.2.1
      - tornado==6.3.2
      - traitlets==5.9.0
      - typing-extensions==4.6.2
      - tzdata==2023.3
      - uri-template==1.2.0
      - urllib3==1.26.16
      - wandb==0.15.3
      - wcwidth==0.2.6
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.5.2
      - werkzeug==2.3.4
      - widgetsnbextension==4.0.7
      - xgboost==1.7.5
      - zipp==3.15.0
prefix: /Users/boisalai/miniconda3/envs/mlops-zoomcamp-env
