wandb_version: 1

max_depth:
  desc: null
  value: 10
random_state:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.3
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1685633190.947812
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.9.16
      5: 0.15.3
      8:
      - 2
      - 5
